<script src="<?= base_url('assets/templates/') ?>vendors/base/vendor.bundle.base.js"></script>
<script src="<?= base_url('assets/templates/') ?>vendors/chart.js/Chart.min.js"></script>
<script src="<?= base_url('assets/templates/') ?>vendors/datatables.net/jquery.dataTables.js"></script>
<script src="<?= base_url('assets/templates/') ?>vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/off-canvas.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/hoverable-collapse.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/template.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/dashboard.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/data-table.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/jquery.dataTables.js"></script>
<script src="<?= base_url('assets/templates/') ?>js/dataTables.bootstrap4.js"></script>